<h1><?= $this->test ?></h1>

<h2>Avant sauvegarde</h2>

<p>Id : <?php echo $this->userFind->getId(); ?></p>
<p>Nom : <?php echo $this->userFind->getName(); ?></p>


<h2>Après sauvegarde</h2>

<p>Id : <?php echo $this->userSave->getId(); ?></p>
<p>Nom : <?php echo $this->userSave->getName(); ?></p>

<h2>User Insert</h2>

<p>Id : <?php echo $this->userInsert->getId(); ?></p>
<p>Nom : <?php echo $this->userInsert->getName(); ?></p>